language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
os:
  - osx
before_install:
  - brew upgrade cmake
script:
  - sh ./build.sh

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
    slack: offercome:bL9KPJxyv6OjNRWJCnFTt59R